output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks-cluster["pp-wg-prod"].cluster_endpoint
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  # value       = local.cluster_name
  value = module.eks-cluster["pp-wg-prod"].cluster_id
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks-cluster["pp-wg-prod"].cluster_security_group_id
}

output "config_map_aws_auth" {
  value = module.eks-cluster["pp-wg-prod"].config_map_aws_auth
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = <<EOF
#==> kubeconfig
${module.eks-cluster["pp-wg-prod"].kubeconfig}
####
  EOF
}

output "region" {
  description = "AWS region"
  value       = local.region
}

output "vpc_id" {
  description = "The ID of the VPC"
  value       = module.vpc.vpc_id
}

output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = module.vpc.public_subnets
}

output "worker_role_arn" {
  value = "${module.eks-cluster["pp-wg-prod"].worker_iam_role_arn}"
}